### ISSUE TITLE
wrong register setting?

### ISSUE THREAD

**Issue by hp9000** [nopnop2002/Arduino-SI4432#1]
si4432.cpp line 245:
In my opinion value '0x4c' is wrong and should read  '0x2c' instead.
Acc. to datasheet bit D6 is 'reserved', bit D5 is the ”txdtrtscale” bit.

**Comment by nopnop2002** [comment]
Thanks for the report.
you are right
i fixed it.
![si4432-70h](https://user-images.githubusercontent.com/6020549/225456392-fcbbc212-c9e0-4cdf-a997-f50995a70d3b.jpg)
