### ISSUE TITLE
values for frequency registers calculated wrongly

### ISSUE THREAD

**Issue by hp9000** [nopnop2002/Arduino-SI4432#2]
second and third value are always 0.
This is because si4432.cpp line 29 is an integer division and fractional part gets lost. Result is 0 for freqcarrier in line 33.

quick fix: change "10" to "10.0" in line 29

**Comment by hp9000** [comment]
better: force compiler to use type double by a cast:
 
double fPart = ((double)baseFrequencyMhz / (10 * (highBand + 1))) - 24;

**Comment by nopnop2002** [comment]
Thanks for the report.
Fixed.
